namespace Window_Project_v5._1.Forms
{
    partial class FHomepage
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FHomepage));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.panelHomepage = new System.Windows.Forms.FlowLayoutPanel();
            this.panelLeft = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnLogOut = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnInformation = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnTrackOrder = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnBuy = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnBuyer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.panelSellerSubmenu = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnOrderAnalysis = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnUpdateOrder = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnSell = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnSeller = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.panelLogo = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.panelLeft.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            this.panelSellerSubmenu.SuspendLayout();
            this.panelLogo.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // panelHomepage
            // 
            this.panelHomepage.BackColor = System.Drawing.Color.WhiteSmoke;
            this.panelHomepage.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelHomepage.Location = new System.Drawing.Point(226, 6);
            this.panelHomepage.Name = "panelHomepage";
            this.panelHomepage.Size = new System.Drawing.Size(907, 613);
            this.panelHomepage.TabIndex = 2;
            // 
            // panelLeft
            // 
            this.panelLeft.BackgroundColor = System.Drawing.Color.Transparent;
            this.panelLeft.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panelLeft.BackgroundImage")));
            this.panelLeft.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panelLeft.BorderColor = System.Drawing.Color.Transparent;
            this.panelLeft.BorderRadius = 1;
            this.panelLeft.BorderThickness = 1;
            this.panelLeft.Controls.Add(this.btnLogOut);
            this.panelLeft.Controls.Add(this.btnInformation);
            this.panelLeft.Controls.Add(this.bunifuPanel1);
            this.panelLeft.Controls.Add(this.btnBuyer);
            this.panelLeft.Controls.Add(this.panelSellerSubmenu);
            this.panelLeft.Controls.Add(this.btnSeller);
            this.panelLeft.Controls.Add(this.panelLogo);
            this.panelLeft.Dock = System.Windows.Forms.DockStyle.Left;
            this.panelLeft.Location = new System.Drawing.Point(6, 6);
            this.panelLeft.Name = "panelLeft";
            this.panelLeft.ShowBorders = true;
            this.panelLeft.Size = new System.Drawing.Size(220, 613);
            this.panelLeft.TabIndex = 0;
            // 
            // btnLogOut
            // 
            this.btnLogOut.AllowAnimations = true;
            this.btnLogOut.AllowMouseEffects = true;
            this.btnLogOut.AllowToggling = false;
            this.btnLogOut.AnimationSpeed = 200;
            this.btnLogOut.AutoGenerateColors = false;
            this.btnLogOut.AutoRoundBorders = false;
            this.btnLogOut.AutoSizeLeftIcon = true;
            this.btnLogOut.AutoSizeRightIcon = true;
            this.btnLogOut.BackColor = System.Drawing.Color.Transparent;
            this.btnLogOut.BackColor1 = System.Drawing.Color.Transparent;
            this.btnLogOut.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLogOut.BackgroundImage")));
            this.btnLogOut.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnLogOut.ButtonText = "Log out";
            this.btnLogOut.ButtonTextMarginLeft = 0;
            this.btnLogOut.ColorContrastOnClick = 45;
            this.btnLogOut.ColorContrastOnHover = 45;
            this.btnLogOut.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnLogOut.CustomizableEdges = borderEdges1;
            this.btnLogOut.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLogOut.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogOut.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogOut.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogOut.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.btnLogOut.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnLogOut.Font = new System.Drawing.Font("Century Gothic", 10.2F, System.Drawing.FontStyle.Bold);
            this.btnLogOut.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnLogOut.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLogOut.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogOut.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btnLogOut.IconMarginLeft = 11;
            this.btnLogOut.IconPadding = 10;
            this.btnLogOut.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLogOut.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogOut.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLogOut.IconSize = 25;
            this.btnLogOut.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnLogOut.IdleBorderRadius = 1;
            this.btnLogOut.IdleBorderThickness = 1;
            this.btnLogOut.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnLogOut.IdleIconLeftImage = global::Window_Project_v5._1.Properties.Resources.exit;
            this.btnLogOut.IdleIconRightImage = null;
            this.btnLogOut.IndicateFocus = false;
            this.btnLogOut.Location = new System.Drawing.Point(0, 562);
            this.btnLogOut.Name = "btnLogOut";
            this.btnLogOut.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogOut.OnDisabledState.BorderRadius = 1;
            this.btnLogOut.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnLogOut.OnDisabledState.BorderThickness = 1;
            this.btnLogOut.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogOut.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogOut.OnDisabledState.IconLeftImage = null;
            this.btnLogOut.OnDisabledState.IconRightImage = null;
            this.btnLogOut.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnLogOut.onHoverState.BorderRadius = 1;
            this.btnLogOut.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnLogOut.onHoverState.BorderThickness = 1;
            this.btnLogOut.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnLogOut.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnLogOut.onHoverState.IconLeftImage = null;
            this.btnLogOut.onHoverState.IconRightImage = null;
            this.btnLogOut.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnLogOut.OnIdleState.BorderRadius = 1;
            this.btnLogOut.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnLogOut.OnIdleState.BorderThickness = 1;
            this.btnLogOut.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnLogOut.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnLogOut.OnIdleState.IconLeftImage = global::Window_Project_v5._1.Properties.Resources.exit;
            this.btnLogOut.OnIdleState.IconRightImage = null;
            this.btnLogOut.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnLogOut.OnPressedState.BorderRadius = 1;
            this.btnLogOut.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnLogOut.OnPressedState.BorderThickness = 1;
            this.btnLogOut.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnLogOut.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnLogOut.OnPressedState.IconLeftImage = null;
            this.btnLogOut.OnPressedState.IconRightImage = null;
            this.btnLogOut.Size = new System.Drawing.Size(220, 51);
            this.btnLogOut.TabIndex = 8;
            this.btnLogOut.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLogOut.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLogOut.TextMarginLeft = 0;
            this.btnLogOut.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnLogOut.UseDefaultRadiusAndThickness = true;
            this.btnLogOut.Click += new System.EventHandler(this.btnLogOut_Click);
            // 
            // btnInformation
            // 
            this.btnInformation.AllowAnimations = true;
            this.btnInformation.AllowMouseEffects = true;
            this.btnInformation.AllowToggling = false;
            this.btnInformation.AnimationSpeed = 200;
            this.btnInformation.AutoGenerateColors = false;
            this.btnInformation.AutoRoundBorders = false;
            this.btnInformation.AutoSizeLeftIcon = true;
            this.btnInformation.AutoSizeRightIcon = true;
            this.btnInformation.BackColor = System.Drawing.Color.Transparent;
            this.btnInformation.BackColor1 = System.Drawing.Color.Transparent;
            this.btnInformation.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnInformation.BackgroundImage")));
            this.btnInformation.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnInformation.ButtonText = "Information";
            this.btnInformation.ButtonTextMarginLeft = 0;
            this.btnInformation.ColorContrastOnClick = 45;
            this.btnInformation.ColorContrastOnHover = 45;
            this.btnInformation.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnInformation.CustomizableEdges = borderEdges2;
            this.btnInformation.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnInformation.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInformation.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInformation.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInformation.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnInformation.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnInformation.Font = new System.Drawing.Font("Century Gothic", 10.2F, System.Drawing.FontStyle.Bold);
            this.btnInformation.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnInformation.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnInformation.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnInformation.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btnInformation.IconMarginLeft = 11;
            this.btnInformation.IconPadding = 10;
            this.btnInformation.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnInformation.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnInformation.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnInformation.IconSize = 25;
            this.btnInformation.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnInformation.IdleBorderRadius = 1;
            this.btnInformation.IdleBorderThickness = 1;
            this.btnInformation.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnInformation.IdleIconLeftImage = global::Window_Project_v5._1.Properties.Resources.info;
            this.btnInformation.IdleIconRightImage = null;
            this.btnInformation.IndicateFocus = false;
            this.btnInformation.Location = new System.Drawing.Point(0, 454);
            this.btnInformation.Name = "btnInformation";
            this.btnInformation.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnInformation.OnDisabledState.BorderRadius = 1;
            this.btnInformation.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnInformation.OnDisabledState.BorderThickness = 1;
            this.btnInformation.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInformation.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInformation.OnDisabledState.IconLeftImage = null;
            this.btnInformation.OnDisabledState.IconRightImage = null;
            this.btnInformation.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnInformation.onHoverState.BorderRadius = 1;
            this.btnInformation.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnInformation.onHoverState.BorderThickness = 1;
            this.btnInformation.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnInformation.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnInformation.onHoverState.IconLeftImage = null;
            this.btnInformation.onHoverState.IconRightImage = null;
            this.btnInformation.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnInformation.OnIdleState.BorderRadius = 1;
            this.btnInformation.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnInformation.OnIdleState.BorderThickness = 1;
            this.btnInformation.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnInformation.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnInformation.OnIdleState.IconLeftImage = global::Window_Project_v5._1.Properties.Resources.info;
            this.btnInformation.OnIdleState.IconRightImage = null;
            this.btnInformation.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnInformation.OnPressedState.BorderRadius = 1;
            this.btnInformation.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnInformation.OnPressedState.BorderThickness = 1;
            this.btnInformation.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnInformation.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnInformation.OnPressedState.IconLeftImage = null;
            this.btnInformation.OnPressedState.IconRightImage = null;
            this.btnInformation.Size = new System.Drawing.Size(220, 51);
            this.btnInformation.TabIndex = 7;
            this.btnInformation.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnInformation.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnInformation.TextMarginLeft = 0;
            this.btnInformation.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnInformation.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(37)))), ((int)(((byte)(110)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.btnTrackOrder);
            this.bunifuPanel1.Controls.Add(this.btnBuy);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 350);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(220, 104);
            this.bunifuPanel1.TabIndex = 6;
            // 
            // btnTrackOrder
            // 
            this.btnTrackOrder.AllowAnimations = true;
            this.btnTrackOrder.AllowMouseEffects = true;
            this.btnTrackOrder.AllowToggling = false;
            this.btnTrackOrder.AnimationSpeed = 200;
            this.btnTrackOrder.AutoGenerateColors = false;
            this.btnTrackOrder.AutoRoundBorders = false;
            this.btnTrackOrder.AutoSizeLeftIcon = true;
            this.btnTrackOrder.AutoSizeRightIcon = true;
            this.btnTrackOrder.BackColor = System.Drawing.Color.Transparent;
            this.btnTrackOrder.BackColor1 = System.Drawing.Color.Transparent;
            this.btnTrackOrder.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTrackOrder.BackgroundImage")));
            this.btnTrackOrder.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnTrackOrder.ButtonText = "Track Order";
            this.btnTrackOrder.ButtonTextMarginLeft = 0;
            this.btnTrackOrder.ColorContrastOnClick = 45;
            this.btnTrackOrder.ColorContrastOnHover = 45;
            this.btnTrackOrder.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnTrackOrder.CustomizableEdges = borderEdges3;
            this.btnTrackOrder.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTrackOrder.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTrackOrder.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTrackOrder.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTrackOrder.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnTrackOrder.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnTrackOrder.Font = new System.Drawing.Font("Century Gothic", 10.2F, System.Drawing.FontStyle.Bold);
            this.btnTrackOrder.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnTrackOrder.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTrackOrder.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnTrackOrder.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btnTrackOrder.IconMarginLeft = 11;
            this.btnTrackOrder.IconPadding = 10;
            this.btnTrackOrder.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTrackOrder.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnTrackOrder.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTrackOrder.IconSize = 25;
            this.btnTrackOrder.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnTrackOrder.IdleBorderRadius = 1;
            this.btnTrackOrder.IdleBorderThickness = 1;
            this.btnTrackOrder.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnTrackOrder.IdleIconLeftImage = global::Window_Project_v5._1.Properties.Resources.tracking;
            this.btnTrackOrder.IdleIconRightImage = null;
            this.btnTrackOrder.IndicateFocus = false;
            this.btnTrackOrder.Location = new System.Drawing.Point(0, 45);
            this.btnTrackOrder.Name = "btnTrackOrder";
            this.btnTrackOrder.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTrackOrder.OnDisabledState.BorderRadius = 1;
            this.btnTrackOrder.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnTrackOrder.OnDisabledState.BorderThickness = 1;
            this.btnTrackOrder.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTrackOrder.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTrackOrder.OnDisabledState.IconLeftImage = null;
            this.btnTrackOrder.OnDisabledState.IconRightImage = null;
            this.btnTrackOrder.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnTrackOrder.onHoverState.BorderRadius = 1;
            this.btnTrackOrder.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnTrackOrder.onHoverState.BorderThickness = 1;
            this.btnTrackOrder.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnTrackOrder.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnTrackOrder.onHoverState.IconLeftImage = null;
            this.btnTrackOrder.onHoverState.IconRightImage = null;
            this.btnTrackOrder.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnTrackOrder.OnIdleState.BorderRadius = 1;
            this.btnTrackOrder.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnTrackOrder.OnIdleState.BorderThickness = 1;
            this.btnTrackOrder.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnTrackOrder.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnTrackOrder.OnIdleState.IconLeftImage = global::Window_Project_v5._1.Properties.Resources.tracking;
            this.btnTrackOrder.OnIdleState.IconRightImage = null;
            this.btnTrackOrder.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnTrackOrder.OnPressedState.BorderRadius = 1;
            this.btnTrackOrder.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnTrackOrder.OnPressedState.BorderThickness = 1;
            this.btnTrackOrder.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnTrackOrder.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnTrackOrder.OnPressedState.IconLeftImage = null;
            this.btnTrackOrder.OnPressedState.IconRightImage = null;
            this.btnTrackOrder.Size = new System.Drawing.Size(220, 45);
            this.btnTrackOrder.TabIndex = 4;
            this.btnTrackOrder.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTrackOrder.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTrackOrder.TextMarginLeft = 0;
            this.btnTrackOrder.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnTrackOrder.UseDefaultRadiusAndThickness = true;
            // 
            // btnBuy
            // 
            this.btnBuy.AllowAnimations = true;
            this.btnBuy.AllowMouseEffects = true;
            this.btnBuy.AllowToggling = false;
            this.btnBuy.AnimationSpeed = 200;
            this.btnBuy.AutoGenerateColors = false;
            this.btnBuy.AutoRoundBorders = false;
            this.btnBuy.AutoSizeLeftIcon = true;
            this.btnBuy.AutoSizeRightIcon = true;
            this.btnBuy.BackColor = System.Drawing.Color.Transparent;
            this.btnBuy.BackColor1 = System.Drawing.Color.Transparent;
            this.btnBuy.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBuy.BackgroundImage")));
            this.btnBuy.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBuy.ButtonText = "Buy";
            this.btnBuy.ButtonTextMarginLeft = 0;
            this.btnBuy.ColorContrastOnClick = 45;
            this.btnBuy.ColorContrastOnHover = 45;
            this.btnBuy.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnBuy.CustomizableEdges = borderEdges4;
            this.btnBuy.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBuy.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBuy.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBuy.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBuy.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnBuy.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnBuy.Font = new System.Drawing.Font("Century Gothic", 10.2F, System.Drawing.FontStyle.Bold);
            this.btnBuy.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnBuy.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBuy.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBuy.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btnBuy.IconMarginLeft = 11;
            this.btnBuy.IconPadding = 10;
            this.btnBuy.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBuy.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBuy.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBuy.IconSize = 25;
            this.btnBuy.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnBuy.IdleBorderRadius = 1;
            this.btnBuy.IdleBorderThickness = 1;
            this.btnBuy.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnBuy.IdleIconLeftImage = global::Window_Project_v5._1.Properties.Resources.shopping_bag;
            this.btnBuy.IdleIconRightImage = null;
            this.btnBuy.IndicateFocus = false;
            this.btnBuy.Location = new System.Drawing.Point(0, 0);
            this.btnBuy.Name = "btnBuy";
            this.btnBuy.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBuy.OnDisabledState.BorderRadius = 1;
            this.btnBuy.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBuy.OnDisabledState.BorderThickness = 1;
            this.btnBuy.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBuy.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBuy.OnDisabledState.IconLeftImage = null;
            this.btnBuy.OnDisabledState.IconRightImage = null;
            this.btnBuy.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnBuy.onHoverState.BorderRadius = 1;
            this.btnBuy.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBuy.onHoverState.BorderThickness = 1;
            this.btnBuy.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnBuy.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnBuy.onHoverState.IconLeftImage = null;
            this.btnBuy.onHoverState.IconRightImage = null;
            this.btnBuy.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnBuy.OnIdleState.BorderRadius = 1;
            this.btnBuy.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBuy.OnIdleState.BorderThickness = 1;
            this.btnBuy.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnBuy.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnBuy.OnIdleState.IconLeftImage = global::Window_Project_v5._1.Properties.Resources.shopping_bag;
            this.btnBuy.OnIdleState.IconRightImage = null;
            this.btnBuy.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnBuy.OnPressedState.BorderRadius = 1;
            this.btnBuy.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBuy.OnPressedState.BorderThickness = 1;
            this.btnBuy.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnBuy.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnBuy.OnPressedState.IconLeftImage = null;
            this.btnBuy.OnPressedState.IconRightImage = null;
            this.btnBuy.Size = new System.Drawing.Size(220, 45);
            this.btnBuy.TabIndex = 3;
            this.btnBuy.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBuy.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBuy.TextMarginLeft = 0;
            this.btnBuy.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnBuy.UseDefaultRadiusAndThickness = true;
            // 
            // btnBuyer
            // 
            this.btnBuyer.AllowAnimations = true;
            this.btnBuyer.AllowMouseEffects = true;
            this.btnBuyer.AllowToggling = false;
            this.btnBuyer.AnimationSpeed = 200;
            this.btnBuyer.AutoGenerateColors = false;
            this.btnBuyer.AutoRoundBorders = false;
            this.btnBuyer.AutoSizeLeftIcon = true;
            this.btnBuyer.AutoSizeRightIcon = true;
            this.btnBuyer.BackColor = System.Drawing.Color.Transparent;
            this.btnBuyer.BackColor1 = System.Drawing.Color.Transparent;
            this.btnBuyer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBuyer.BackgroundImage")));
            this.btnBuyer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBuyer.ButtonText = "Buyer";
            this.btnBuyer.ButtonTextMarginLeft = 0;
            this.btnBuyer.ColorContrastOnClick = 45;
            this.btnBuyer.ColorContrastOnHover = 45;
            this.btnBuyer.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnBuyer.CustomizableEdges = borderEdges5;
            this.btnBuyer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBuyer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBuyer.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBuyer.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBuyer.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnBuyer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnBuyer.Font = new System.Drawing.Font("Century Gothic", 10.2F, System.Drawing.FontStyle.Bold);
            this.btnBuyer.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnBuyer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBuyer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBuyer.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btnBuyer.IconMarginLeft = 11;
            this.btnBuyer.IconPadding = 10;
            this.btnBuyer.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBuyer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBuyer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBuyer.IconSize = 25;
            this.btnBuyer.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnBuyer.IdleBorderRadius = 1;
            this.btnBuyer.IdleBorderThickness = 1;
            this.btnBuyer.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnBuyer.IdleIconLeftImage = global::Window_Project_v5._1.Properties.Resources.cart;
            this.btnBuyer.IdleIconRightImage = null;
            this.btnBuyer.IndicateFocus = false;
            this.btnBuyer.Location = new System.Drawing.Point(0, 299);
            this.btnBuyer.Name = "btnBuyer";
            this.btnBuyer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBuyer.OnDisabledState.BorderRadius = 1;
            this.btnBuyer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBuyer.OnDisabledState.BorderThickness = 1;
            this.btnBuyer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBuyer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBuyer.OnDisabledState.IconLeftImage = null;
            this.btnBuyer.OnDisabledState.IconRightImage = null;
            this.btnBuyer.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnBuyer.onHoverState.BorderRadius = 1;
            this.btnBuyer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBuyer.onHoverState.BorderThickness = 1;
            this.btnBuyer.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnBuyer.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnBuyer.onHoverState.IconLeftImage = null;
            this.btnBuyer.onHoverState.IconRightImage = null;
            this.btnBuyer.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnBuyer.OnIdleState.BorderRadius = 1;
            this.btnBuyer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBuyer.OnIdleState.BorderThickness = 1;
            this.btnBuyer.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnBuyer.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnBuyer.OnIdleState.IconLeftImage = global::Window_Project_v5._1.Properties.Resources.cart;
            this.btnBuyer.OnIdleState.IconRightImage = null;
            this.btnBuyer.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnBuyer.OnPressedState.BorderRadius = 1;
            this.btnBuyer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBuyer.OnPressedState.BorderThickness = 1;
            this.btnBuyer.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnBuyer.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnBuyer.OnPressedState.IconLeftImage = null;
            this.btnBuyer.OnPressedState.IconRightImage = null;
            this.btnBuyer.Size = new System.Drawing.Size(220, 51);
            this.btnBuyer.TabIndex = 3;
            this.btnBuyer.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBuyer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBuyer.TextMarginLeft = 0;
            this.btnBuyer.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnBuyer.UseDefaultRadiusAndThickness = true;
            // 
            // panelSellerSubmenu
            // 
            this.panelSellerSubmenu.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(37)))), ((int)(((byte)(110)))));
            this.panelSellerSubmenu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panelSellerSubmenu.BackgroundImage")));
            this.panelSellerSubmenu.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panelSellerSubmenu.BorderColor = System.Drawing.Color.Transparent;
            this.panelSellerSubmenu.BorderRadius = 3;
            this.panelSellerSubmenu.BorderThickness = 1;
            this.panelSellerSubmenu.Controls.Add(this.btnOrderAnalysis);
            this.panelSellerSubmenu.Controls.Add(this.btnUpdateOrder);
            this.panelSellerSubmenu.Controls.Add(this.btnSell);
            this.panelSellerSubmenu.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelSellerSubmenu.Location = new System.Drawing.Point(0, 151);
            this.panelSellerSubmenu.Name = "panelSellerSubmenu";
            this.panelSellerSubmenu.ShowBorders = true;
            this.panelSellerSubmenu.Size = new System.Drawing.Size(220, 148);
            this.panelSellerSubmenu.TabIndex = 2;
            // 
            // btnOrderAnalysis
            // 
            this.btnOrderAnalysis.AllowAnimations = true;
            this.btnOrderAnalysis.AllowMouseEffects = true;
            this.btnOrderAnalysis.AllowToggling = false;
            this.btnOrderAnalysis.AnimationSpeed = 200;
            this.btnOrderAnalysis.AutoGenerateColors = false;
            this.btnOrderAnalysis.AutoRoundBorders = false;
            this.btnOrderAnalysis.AutoSizeLeftIcon = true;
            this.btnOrderAnalysis.AutoSizeRightIcon = true;
            this.btnOrderAnalysis.BackColor = System.Drawing.Color.Transparent;
            this.btnOrderAnalysis.BackColor1 = System.Drawing.Color.Transparent;
            this.btnOrderAnalysis.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOrderAnalysis.BackgroundImage")));
            this.btnOrderAnalysis.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnOrderAnalysis.ButtonText = "Order Analysis";
            this.btnOrderAnalysis.ButtonTextMarginLeft = 0;
            this.btnOrderAnalysis.ColorContrastOnClick = 45;
            this.btnOrderAnalysis.ColorContrastOnHover = 45;
            this.btnOrderAnalysis.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnOrderAnalysis.CustomizableEdges = borderEdges6;
            this.btnOrderAnalysis.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOrderAnalysis.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOrderAnalysis.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOrderAnalysis.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOrderAnalysis.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnOrderAnalysis.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnOrderAnalysis.Font = new System.Drawing.Font("Century Gothic", 10.2F, System.Drawing.FontStyle.Bold);
            this.btnOrderAnalysis.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnOrderAnalysis.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOrderAnalysis.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOrderAnalysis.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btnOrderAnalysis.IconMarginLeft = 11;
            this.btnOrderAnalysis.IconPadding = 10;
            this.btnOrderAnalysis.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOrderAnalysis.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOrderAnalysis.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOrderAnalysis.IconSize = 25;
            this.btnOrderAnalysis.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnOrderAnalysis.IdleBorderRadius = 1;
            this.btnOrderAnalysis.IdleBorderThickness = 1;
            this.btnOrderAnalysis.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnOrderAnalysis.IdleIconLeftImage = global::Window_Project_v5._1.Properties.Resources.web_analytics;
            this.btnOrderAnalysis.IdleIconRightImage = null;
            this.btnOrderAnalysis.IndicateFocus = false;
            this.btnOrderAnalysis.Location = new System.Drawing.Point(0, 90);
            this.btnOrderAnalysis.Name = "btnOrderAnalysis";
            this.btnOrderAnalysis.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOrderAnalysis.OnDisabledState.BorderRadius = 1;
            this.btnOrderAnalysis.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnOrderAnalysis.OnDisabledState.BorderThickness = 1;
            this.btnOrderAnalysis.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOrderAnalysis.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOrderAnalysis.OnDisabledState.IconLeftImage = null;
            this.btnOrderAnalysis.OnDisabledState.IconRightImage = null;
            this.btnOrderAnalysis.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnOrderAnalysis.onHoverState.BorderRadius = 1;
            this.btnOrderAnalysis.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnOrderAnalysis.onHoverState.BorderThickness = 1;
            this.btnOrderAnalysis.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnOrderAnalysis.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnOrderAnalysis.onHoverState.IconLeftImage = null;
            this.btnOrderAnalysis.onHoverState.IconRightImage = null;
            this.btnOrderAnalysis.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnOrderAnalysis.OnIdleState.BorderRadius = 1;
            this.btnOrderAnalysis.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnOrderAnalysis.OnIdleState.BorderThickness = 1;
            this.btnOrderAnalysis.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnOrderAnalysis.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnOrderAnalysis.OnIdleState.IconLeftImage = global::Window_Project_v5._1.Properties.Resources.web_analytics;
            this.btnOrderAnalysis.OnIdleState.IconRightImage = null;
            this.btnOrderAnalysis.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnOrderAnalysis.OnPressedState.BorderRadius = 1;
            this.btnOrderAnalysis.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnOrderAnalysis.OnPressedState.BorderThickness = 1;
            this.btnOrderAnalysis.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnOrderAnalysis.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnOrderAnalysis.OnPressedState.IconLeftImage = null;
            this.btnOrderAnalysis.OnPressedState.IconRightImage = null;
            this.btnOrderAnalysis.Size = new System.Drawing.Size(220, 45);
            this.btnOrderAnalysis.TabIndex = 5;
            this.btnOrderAnalysis.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOrderAnalysis.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOrderAnalysis.TextMarginLeft = 0;
            this.btnOrderAnalysis.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnOrderAnalysis.UseDefaultRadiusAndThickness = true;
            // 
            // btnUpdateOrder
            // 
            this.btnUpdateOrder.AllowAnimations = true;
            this.btnUpdateOrder.AllowMouseEffects = true;
            this.btnUpdateOrder.AllowToggling = false;
            this.btnUpdateOrder.AnimationSpeed = 200;
            this.btnUpdateOrder.AutoGenerateColors = false;
            this.btnUpdateOrder.AutoRoundBorders = false;
            this.btnUpdateOrder.AutoSizeLeftIcon = true;
            this.btnUpdateOrder.AutoSizeRightIcon = true;
            this.btnUpdateOrder.BackColor = System.Drawing.Color.Transparent;
            this.btnUpdateOrder.BackColor1 = System.Drawing.Color.Transparent;
            this.btnUpdateOrder.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUpdateOrder.BackgroundImage")));
            this.btnUpdateOrder.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUpdateOrder.ButtonText = "Update Order";
            this.btnUpdateOrder.ButtonTextMarginLeft = 0;
            this.btnUpdateOrder.ColorContrastOnClick = 45;
            this.btnUpdateOrder.ColorContrastOnHover = 45;
            this.btnUpdateOrder.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnUpdateOrder.CustomizableEdges = borderEdges7;
            this.btnUpdateOrder.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUpdateOrder.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUpdateOrder.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUpdateOrder.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUpdateOrder.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnUpdateOrder.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnUpdateOrder.Font = new System.Drawing.Font("Century Gothic", 10.2F, System.Drawing.FontStyle.Bold);
            this.btnUpdateOrder.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnUpdateOrder.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUpdateOrder.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUpdateOrder.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btnUpdateOrder.IconMarginLeft = 11;
            this.btnUpdateOrder.IconPadding = 10;
            this.btnUpdateOrder.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUpdateOrder.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUpdateOrder.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUpdateOrder.IconSize = 25;
            this.btnUpdateOrder.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnUpdateOrder.IdleBorderRadius = 1;
            this.btnUpdateOrder.IdleBorderThickness = 1;
            this.btnUpdateOrder.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnUpdateOrder.IdleIconLeftImage = global::Window_Project_v5._1.Properties.Resources.real_time;
            this.btnUpdateOrder.IdleIconRightImage = null;
            this.btnUpdateOrder.IndicateFocus = false;
            this.btnUpdateOrder.Location = new System.Drawing.Point(0, 45);
            this.btnUpdateOrder.Name = "btnUpdateOrder";
            this.btnUpdateOrder.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUpdateOrder.OnDisabledState.BorderRadius = 1;
            this.btnUpdateOrder.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUpdateOrder.OnDisabledState.BorderThickness = 1;
            this.btnUpdateOrder.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUpdateOrder.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUpdateOrder.OnDisabledState.IconLeftImage = null;
            this.btnUpdateOrder.OnDisabledState.IconRightImage = null;
            this.btnUpdateOrder.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnUpdateOrder.onHoverState.BorderRadius = 1;
            this.btnUpdateOrder.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUpdateOrder.onHoverState.BorderThickness = 1;
            this.btnUpdateOrder.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnUpdateOrder.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnUpdateOrder.onHoverState.IconLeftImage = null;
            this.btnUpdateOrder.onHoverState.IconRightImage = null;
            this.btnUpdateOrder.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnUpdateOrder.OnIdleState.BorderRadius = 1;
            this.btnUpdateOrder.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUpdateOrder.OnIdleState.BorderThickness = 1;
            this.btnUpdateOrder.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnUpdateOrder.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnUpdateOrder.OnIdleState.IconLeftImage = global::Window_Project_v5._1.Properties.Resources.real_time;
            this.btnUpdateOrder.OnIdleState.IconRightImage = null;
            this.btnUpdateOrder.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnUpdateOrder.OnPressedState.BorderRadius = 1;
            this.btnUpdateOrder.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUpdateOrder.OnPressedState.BorderThickness = 1;
            this.btnUpdateOrder.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnUpdateOrder.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnUpdateOrder.OnPressedState.IconLeftImage = null;
            this.btnUpdateOrder.OnPressedState.IconRightImage = null;
            this.btnUpdateOrder.Size = new System.Drawing.Size(220, 45);
            this.btnUpdateOrder.TabIndex = 4;
            this.btnUpdateOrder.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUpdateOrder.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUpdateOrder.TextMarginLeft = 0;
            this.btnUpdateOrder.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnUpdateOrder.UseDefaultRadiusAndThickness = true;
            // 
            // btnSell
            // 
            this.btnSell.AllowAnimations = true;
            this.btnSell.AllowMouseEffects = true;
            this.btnSell.AllowToggling = false;
            this.btnSell.AnimationSpeed = 200;
            this.btnSell.AutoGenerateColors = false;
            this.btnSell.AutoRoundBorders = false;
            this.btnSell.AutoSizeLeftIcon = true;
            this.btnSell.AutoSizeRightIcon = true;
            this.btnSell.BackColor = System.Drawing.Color.Transparent;
            this.btnSell.BackColor1 = System.Drawing.Color.Transparent;
            this.btnSell.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSell.BackgroundImage")));
            this.btnSell.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSell.ButtonText = "Sell";
            this.btnSell.ButtonTextMarginLeft = 0;
            this.btnSell.ColorContrastOnClick = 45;
            this.btnSell.ColorContrastOnHover = 45;
            this.btnSell.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnSell.CustomizableEdges = borderEdges8;
            this.btnSell.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSell.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSell.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSell.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSell.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnSell.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnSell.Font = new System.Drawing.Font("Century Gothic", 10.2F, System.Drawing.FontStyle.Bold);
            this.btnSell.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnSell.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSell.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSell.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btnSell.IconMarginLeft = 11;
            this.btnSell.IconPadding = 10;
            this.btnSell.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSell.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSell.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSell.IconSize = 25;
            this.btnSell.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnSell.IdleBorderRadius = 1;
            this.btnSell.IdleBorderThickness = 1;
            this.btnSell.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnSell.IdleIconLeftImage = global::Window_Project_v5._1.Properties.Resources.hand;
            this.btnSell.IdleIconRightImage = null;
            this.btnSell.IndicateFocus = false;
            this.btnSell.Location = new System.Drawing.Point(0, 0);
            this.btnSell.Name = "btnSell";
            this.btnSell.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSell.OnDisabledState.BorderRadius = 1;
            this.btnSell.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSell.OnDisabledState.BorderThickness = 1;
            this.btnSell.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSell.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSell.OnDisabledState.IconLeftImage = null;
            this.btnSell.OnDisabledState.IconRightImage = null;
            this.btnSell.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnSell.onHoverState.BorderRadius = 1;
            this.btnSell.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSell.onHoverState.BorderThickness = 1;
            this.btnSell.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnSell.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnSell.onHoverState.IconLeftImage = null;
            this.btnSell.onHoverState.IconRightImage = null;
            this.btnSell.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnSell.OnIdleState.BorderRadius = 1;
            this.btnSell.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSell.OnIdleState.BorderThickness = 1;
            this.btnSell.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnSell.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnSell.OnIdleState.IconLeftImage = global::Window_Project_v5._1.Properties.Resources.hand;
            this.btnSell.OnIdleState.IconRightImage = null;
            this.btnSell.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnSell.OnPressedState.BorderRadius = 1;
            this.btnSell.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSell.OnPressedState.BorderThickness = 1;
            this.btnSell.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnSell.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnSell.OnPressedState.IconLeftImage = null;
            this.btnSell.OnPressedState.IconRightImage = null;
            this.btnSell.Size = new System.Drawing.Size(220, 45);
            this.btnSell.TabIndex = 3;
            this.btnSell.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSell.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSell.TextMarginLeft = 0;
            this.btnSell.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnSell.UseDefaultRadiusAndThickness = true;
            // 
            // btnSeller
            // 
            this.btnSeller.AllowAnimations = true;
            this.btnSeller.AllowMouseEffects = true;
            this.btnSeller.AllowToggling = false;
            this.btnSeller.AnimationSpeed = 200;
            this.btnSeller.AutoGenerateColors = false;
            this.btnSeller.AutoRoundBorders = false;
            this.btnSeller.AutoSizeLeftIcon = true;
            this.btnSeller.AutoSizeRightIcon = true;
            this.btnSeller.BackColor = System.Drawing.Color.Transparent;
            this.btnSeller.BackColor1 = System.Drawing.Color.Transparent;
            this.btnSeller.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSeller.BackgroundImage")));
            this.btnSeller.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSeller.ButtonText = "Seller";
            this.btnSeller.ButtonTextMarginLeft = 0;
            this.btnSeller.ColorContrastOnClick = 45;
            this.btnSeller.ColorContrastOnHover = 45;
            this.btnSeller.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnSeller.CustomizableEdges = borderEdges9;
            this.btnSeller.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSeller.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSeller.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSeller.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSeller.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnSeller.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnSeller.Font = new System.Drawing.Font("Century Gothic", 10.2F, System.Drawing.FontStyle.Bold);
            this.btnSeller.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnSeller.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSeller.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSeller.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btnSeller.IconMarginLeft = 11;
            this.btnSeller.IconPadding = 10;
            this.btnSeller.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSeller.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSeller.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSeller.IconSize = 25;
            this.btnSeller.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnSeller.IdleBorderRadius = 1;
            this.btnSeller.IdleBorderThickness = 1;
            this.btnSeller.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnSeller.IdleIconLeftImage = global::Window_Project_v5._1.Properties.Resources.writing_white;
            this.btnSeller.IdleIconRightImage = null;
            this.btnSeller.IndicateFocus = false;
            this.btnSeller.Location = new System.Drawing.Point(0, 100);
            this.btnSeller.Name = "btnSeller";
            this.btnSeller.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSeller.OnDisabledState.BorderRadius = 1;
            this.btnSeller.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSeller.OnDisabledState.BorderThickness = 1;
            this.btnSeller.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSeller.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSeller.OnDisabledState.IconLeftImage = null;
            this.btnSeller.OnDisabledState.IconRightImage = null;
            this.btnSeller.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnSeller.onHoverState.BorderRadius = 1;
            this.btnSeller.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSeller.onHoverState.BorderThickness = 1;
            this.btnSeller.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnSeller.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnSeller.onHoverState.IconLeftImage = null;
            this.btnSeller.onHoverState.IconRightImage = null;
            this.btnSeller.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnSeller.OnIdleState.BorderRadius = 1;
            this.btnSeller.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSeller.OnIdleState.BorderThickness = 1;
            this.btnSeller.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnSeller.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnSeller.OnIdleState.IconLeftImage = global::Window_Project_v5._1.Properties.Resources.writing_white;
            this.btnSeller.OnIdleState.IconRightImage = null;
            this.btnSeller.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnSeller.OnPressedState.BorderRadius = 1;
            this.btnSeller.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSeller.OnPressedState.BorderThickness = 1;
            this.btnSeller.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(193)))), ((int)(((byte)(0)))));
            this.btnSeller.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(250)))), ((int)(((byte)(253)))));
            this.btnSeller.OnPressedState.IconLeftImage = null;
            this.btnSeller.OnPressedState.IconRightImage = null;
            this.btnSeller.Size = new System.Drawing.Size(220, 51);
            this.btnSeller.TabIndex = 1;
            this.btnSeller.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSeller.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSeller.TextMarginLeft = 0;
            this.btnSeller.TextPadding = new System.Windows.Forms.Padding(50, 0, 0, 0);
            this.btnSeller.UseDefaultRadiusAndThickness = true;
            // 
            // panelLogo
            // 
            this.panelLogo.BackgroundColor = System.Drawing.Color.Transparent;
            this.panelLogo.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panelLogo.BackgroundImage")));
            this.panelLogo.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panelLogo.BorderColor = System.Drawing.Color.Transparent;
            this.panelLogo.BorderRadius = 3;
            this.panelLogo.BorderThickness = 1;
            this.panelLogo.Controls.Add(this.bunifuPictureBox1);
            this.panelLogo.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelLogo.Location = new System.Drawing.Point(0, 0);
            this.panelLogo.Name = "panelLogo";
            this.panelLogo.ShowBorders = true;
            this.panelLogo.Size = new System.Drawing.Size(220, 100);
            this.panelLogo.TabIndex = 0;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 35;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(22, 12);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(70, 70);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 0;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // FHomepage
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(50)))), ((int)(((byte)(132)))));
            this.ClientSize = new System.Drawing.Size(1139, 625);
            this.Controls.Add(this.panelHomepage);
            this.Controls.Add(this.panelLeft);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.MinimumSize = new System.Drawing.Size(950, 600);
            this.Name = "FHomepage";
            this.Padding = new System.Windows.Forms.Padding(6);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FHomepage";
            this.panelLeft.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.panelSellerSubmenu.ResumeLayout(false);
            this.panelLogo.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel panelLeft;
        private System.Windows.Forms.FlowLayoutPanel panelHomepage;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnSeller;
        private Bunifu.UI.WinForms.BunifuPanel panelLogo;
        private Bunifu.UI.WinForms.BunifuPanel panelSellerSubmenu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnSell;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnLogOut;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnInformation;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnTrackOrder;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnBuy;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnBuyer;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnOrderAnalysis;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnUpdateOrder;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
    }
}