namespace Window_Project_v5._1.Forms
{
    partial class FMoney
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FMoney));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.gbInfo = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.lblTotalMoney = new System.Windows.Forms.Label();
            this.lblName = new System.Windows.Forms.Label();
            this.gbFunction = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.txtPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnWithdraw = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnRecharge = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.txtMoney = new Bunifu.UI.WinForms.BunifuTextBox();
            this.pbMoneyAmount = new System.Windows.Forms.PictureBox();
            this.pbMoneyTotal = new System.Windows.Forms.PictureBox();
            this.pbAvatar = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.panelTop = new System.Windows.Forms.Panel();
            this.panelBody = new System.Windows.Forms.Panel();
            this.btn50 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btn100 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btn200 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btn500 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.gbInfo.SuspendLayout();
            this.gbFunction.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbMoneyAmount)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbMoneyTotal)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbAvatar)).BeginInit();
            this.panelTop.SuspendLayout();
            this.panelBody.SuspendLayout();
            this.SuspendLayout();
            // 
            // gbInfo
            // 
            this.gbInfo.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(50)))), ((int)(((byte)(132)))));
            this.gbInfo.BorderRadius = 20;
            this.gbInfo.BorderThickness = 1;
            this.gbInfo.Controls.Add(this.lblTotalMoney);
            this.gbInfo.Controls.Add(this.pbMoneyTotal);
            this.gbInfo.Controls.Add(this.pbAvatar);
            this.gbInfo.Controls.Add(this.lblName);
            this.gbInfo.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.gbInfo.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.gbInfo.LabelIndent = 10;
            this.gbInfo.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.gbInfo.Location = new System.Drawing.Point(5, 6);
            this.gbInfo.Margin = new System.Windows.Forms.Padding(2, 16, 2, 2);
            this.gbInfo.Name = "gbInfo";
            this.gbInfo.Padding = new System.Windows.Forms.Padding(2);
            this.gbInfo.Size = new System.Drawing.Size(914, 94);
            this.gbInfo.TabIndex = 2;
            this.gbInfo.TabStop = false;
            // 
            // lblTotalMoney
            // 
            this.lblTotalMoney.AutoSize = true;
            this.lblTotalMoney.BackColor = System.Drawing.Color.WhiteSmoke;
            this.lblTotalMoney.Font = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.lblTotalMoney.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(50)))), ((int)(((byte)(132)))));
            this.lblTotalMoney.Location = new System.Drawing.Point(656, 33);
            this.lblTotalMoney.Name = "lblTotalMoney";
            this.lblTotalMoney.Size = new System.Drawing.Size(120, 25);
            this.lblTotalMoney.TabIndex = 12;
            this.lblTotalMoney.Text = "100,000 VND";
            // 
            // lblName
            // 
            this.lblName.AutoSize = true;
            this.lblName.BackColor = System.Drawing.Color.WhiteSmoke;
            this.lblName.Font = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.lblName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(50)))), ((int)(((byte)(132)))));
            this.lblName.Location = new System.Drawing.Point(118, 33);
            this.lblName.Name = "lblName";
            this.lblName.Size = new System.Drawing.Size(140, 25);
            this.lblName.TabIndex = 10;
            this.lblName.Text = "Nguyen Van A";
            // 
            // gbFunction
            // 
            this.gbFunction.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(50)))), ((int)(((byte)(132)))));
            this.gbFunction.BorderRadius = 50;
            this.gbFunction.BorderThickness = 1;
            this.gbFunction.Controls.Add(this.btn500);
            this.gbFunction.Controls.Add(this.btn200);
            this.gbFunction.Controls.Add(this.btn100);
            this.gbFunction.Controls.Add(this.btn50);
            this.gbFunction.Controls.Add(this.pictureBox1);
            this.gbFunction.Controls.Add(this.txtPassword);
            this.gbFunction.Controls.Add(this.btnWithdraw);
            this.gbFunction.Controls.Add(this.btnRecharge);
            this.gbFunction.Controls.Add(this.txtMoney);
            this.gbFunction.Controls.Add(this.pbMoneyAmount);
            this.gbFunction.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.gbFunction.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.gbFunction.LabelIndent = 10;
            this.gbFunction.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.gbFunction.Location = new System.Drawing.Point(5, 15);
            this.gbFunction.Name = "gbFunction";
            this.gbFunction.Size = new System.Drawing.Size(914, 390);
            this.gbFunction.TabIndex = 3;
            this.gbFunction.TabStop = false;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = global::Window_Project_v5._1.Properties.Resources.password;
            this.pictureBox1.Location = new System.Drawing.Point(178, 139);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(80, 80);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 5;
            this.pictureBox1.TabStop = false;
            // 
            // txtPassword
            // 
            this.txtPassword.AcceptsReturn = false;
            this.txtPassword.AcceptsTab = false;
            this.txtPassword.AnimationSpeed = 200;
            this.txtPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPassword.AutoSizeHeight = true;
            this.txtPassword.BackColor = System.Drawing.Color.Transparent;
            this.txtPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPassword.BackgroundImage")));
            this.txtPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPassword.BorderRadius = 40;
            this.txtPassword.BorderThickness = 1;
            this.txtPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtPassword.DefaultText = "";
            this.txtPassword.FillColor = System.Drawing.Color.White;
            this.txtPassword.HideSelection = true;
            this.txtPassword.IconLeft = null;
            this.txtPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.IconPadding = 10;
            this.txtPassword.IconRight = null;
            this.txtPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.Lines = new string[0];
            this.txtPassword.Location = new System.Drawing.Point(295, 162);
            this.txtPassword.MaxLength = 32767;
            this.txtPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPassword.Modified = false;
            this.txtPassword.Multiline = false;
            this.txtPassword.Name = "txtPassword";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPassword.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnIdleState = stateProperties4;
            this.txtPassword.Padding = new System.Windows.Forms.Padding(3);
            this.txtPassword.PasswordChar = '●';
            this.txtPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPassword.PlaceholderText = "Confirm your password";
            this.txtPassword.ReadOnly = false;
            this.txtPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPassword.SelectedText = "";
            this.txtPassword.SelectionLength = 0;
            this.txtPassword.SelectionStart = 0;
            this.txtPassword.ShortcutsEnabled = true;
            this.txtPassword.Size = new System.Drawing.Size(249, 39);
            this.txtPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPassword.TabIndex = 4;
            this.txtPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPassword.TextMarginBottom = 0;
            this.txtPassword.TextMarginLeft = 3;
            this.txtPassword.TextMarginTop = 1;
            this.txtPassword.TextPlaceholder = "Confirm your password";
            this.txtPassword.UseSystemPasswordChar = true;
            this.txtPassword.WordWrap = true;
            // 
            // btnWithdraw
            // 
            this.btnWithdraw.AllowAnimations = true;
            this.btnWithdraw.AllowMouseEffects = true;
            this.btnWithdraw.AllowToggling = false;
            this.btnWithdraw.AnimationSpeed = 200;
            this.btnWithdraw.AutoGenerateColors = false;
            this.btnWithdraw.AutoRoundBorders = false;
            this.btnWithdraw.AutoSizeLeftIcon = true;
            this.btnWithdraw.AutoSizeRightIcon = true;
            this.btnWithdraw.BackColor = System.Drawing.Color.Transparent;
            this.btnWithdraw.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(134)))), ((int)(((byte)(255)))));
            this.btnWithdraw.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnWithdraw.BackgroundImage")));
            this.btnWithdraw.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnWithdraw.ButtonText = "Withdraw";
            this.btnWithdraw.ButtonTextMarginLeft = 0;
            this.btnWithdraw.ColorContrastOnClick = 45;
            this.btnWithdraw.ColorContrastOnHover = 45;
            this.btnWithdraw.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnWithdraw.CustomizableEdges = borderEdges5;
            this.btnWithdraw.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnWithdraw.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnWithdraw.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnWithdraw.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnWithdraw.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnWithdraw.Font = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Bold);
            this.btnWithdraw.ForeColor = System.Drawing.Color.White;
            this.btnWithdraw.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnWithdraw.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnWithdraw.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnWithdraw.IconMarginLeft = 11;
            this.btnWithdraw.IconPadding = 10;
            this.btnWithdraw.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnWithdraw.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnWithdraw.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnWithdraw.IconSize = 25;
            this.btnWithdraw.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(134)))), ((int)(((byte)(255)))));
            this.btnWithdraw.IdleBorderRadius = 25;
            this.btnWithdraw.IdleBorderThickness = 1;
            this.btnWithdraw.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(134)))), ((int)(((byte)(255)))));
            this.btnWithdraw.IdleIconLeftImage = global::Window_Project_v5._1.Properties.Resources.withdraw;
            this.btnWithdraw.IdleIconRightImage = null;
            this.btnWithdraw.IndicateFocus = false;
            this.btnWithdraw.Location = new System.Drawing.Point(394, 241);
            this.btnWithdraw.Name = "btnWithdraw";
            this.btnWithdraw.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnWithdraw.OnDisabledState.BorderRadius = 25;
            this.btnWithdraw.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnWithdraw.OnDisabledState.BorderThickness = 1;
            this.btnWithdraw.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnWithdraw.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnWithdraw.OnDisabledState.IconLeftImage = null;
            this.btnWithdraw.OnDisabledState.IconRightImage = null;
            this.btnWithdraw.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnWithdraw.onHoverState.BorderRadius = 25;
            this.btnWithdraw.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnWithdraw.onHoverState.BorderThickness = 1;
            this.btnWithdraw.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnWithdraw.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnWithdraw.onHoverState.IconLeftImage = null;
            this.btnWithdraw.onHoverState.IconRightImage = null;
            this.btnWithdraw.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(134)))), ((int)(((byte)(255)))));
            this.btnWithdraw.OnIdleState.BorderRadius = 25;
            this.btnWithdraw.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnWithdraw.OnIdleState.BorderThickness = 1;
            this.btnWithdraw.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(58)))), ((int)(((byte)(134)))), ((int)(((byte)(255)))));
            this.btnWithdraw.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnWithdraw.OnIdleState.IconLeftImage = global::Window_Project_v5._1.Properties.Resources.withdraw;
            this.btnWithdraw.OnIdleState.IconRightImage = null;
            this.btnWithdraw.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnWithdraw.OnPressedState.BorderRadius = 25;
            this.btnWithdraw.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnWithdraw.OnPressedState.BorderThickness = 1;
            this.btnWithdraw.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnWithdraw.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnWithdraw.OnPressedState.IconLeftImage = null;
            this.btnWithdraw.OnPressedState.IconRightImage = null;
            this.btnWithdraw.Size = new System.Drawing.Size(150, 39);
            this.btnWithdraw.TabIndex = 3;
            this.btnWithdraw.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnWithdraw.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnWithdraw.TextMarginLeft = 0;
            this.btnWithdraw.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnWithdraw.UseDefaultRadiusAndThickness = true;
            this.btnWithdraw.Click += new System.EventHandler(this.btnWithdraw_Click);
            // 
            // btnRecharge
            // 
            this.btnRecharge.AllowAnimations = true;
            this.btnRecharge.AllowMouseEffects = true;
            this.btnRecharge.AllowToggling = false;
            this.btnRecharge.AnimationSpeed = 200;
            this.btnRecharge.AutoGenerateColors = false;
            this.btnRecharge.AutoRoundBorders = false;
            this.btnRecharge.AutoSizeLeftIcon = true;
            this.btnRecharge.AutoSizeRightIcon = true;
            this.btnRecharge.BackColor = System.Drawing.Color.Transparent;
            this.btnRecharge.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(107)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.btnRecharge.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRecharge.BackgroundImage")));
            this.btnRecharge.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnRecharge.ButtonText = "Recharge";
            this.btnRecharge.ButtonTextMarginLeft = 0;
            this.btnRecharge.ColorContrastOnClick = 45;
            this.btnRecharge.ColorContrastOnHover = 45;
            this.btnRecharge.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnRecharge.CustomizableEdges = borderEdges6;
            this.btnRecharge.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRecharge.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRecharge.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRecharge.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRecharge.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnRecharge.Font = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Bold);
            this.btnRecharge.ForeColor = System.Drawing.Color.White;
            this.btnRecharge.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRecharge.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRecharge.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnRecharge.IconMarginLeft = 11;
            this.btnRecharge.IconPadding = 10;
            this.btnRecharge.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRecharge.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRecharge.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRecharge.IconSize = 25;
            this.btnRecharge.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(107)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.btnRecharge.IdleBorderRadius = 25;
            this.btnRecharge.IdleBorderThickness = 1;
            this.btnRecharge.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(107)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.btnRecharge.IdleIconLeftImage = global::Window_Project_v5._1.Properties.Resources.recharge;
            this.btnRecharge.IdleIconRightImage = null;
            this.btnRecharge.IndicateFocus = false;
            this.btnRecharge.Location = new System.Drawing.Point(178, 241);
            this.btnRecharge.Name = "btnRecharge";
            this.btnRecharge.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRecharge.OnDisabledState.BorderRadius = 25;
            this.btnRecharge.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnRecharge.OnDisabledState.BorderThickness = 1;
            this.btnRecharge.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRecharge.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRecharge.OnDisabledState.IconLeftImage = null;
            this.btnRecharge.OnDisabledState.IconRightImage = null;
            this.btnRecharge.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRecharge.onHoverState.BorderRadius = 25;
            this.btnRecharge.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnRecharge.onHoverState.BorderThickness = 1;
            this.btnRecharge.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRecharge.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnRecharge.onHoverState.IconLeftImage = null;
            this.btnRecharge.onHoverState.IconRightImage = null;
            this.btnRecharge.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(107)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.btnRecharge.OnIdleState.BorderRadius = 25;
            this.btnRecharge.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnRecharge.OnIdleState.BorderThickness = 1;
            this.btnRecharge.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(107)))), ((int)(((byte)(58)))), ((int)(((byte)(255)))));
            this.btnRecharge.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnRecharge.OnIdleState.IconLeftImage = global::Window_Project_v5._1.Properties.Resources.recharge;
            this.btnRecharge.OnIdleState.IconRightImage = null;
            this.btnRecharge.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRecharge.OnPressedState.BorderRadius = 25;
            this.btnRecharge.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnRecharge.OnPressedState.BorderThickness = 1;
            this.btnRecharge.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRecharge.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnRecharge.OnPressedState.IconLeftImage = null;
            this.btnRecharge.OnPressedState.IconRightImage = null;
            this.btnRecharge.Size = new System.Drawing.Size(150, 39);
            this.btnRecharge.TabIndex = 2;
            this.btnRecharge.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRecharge.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRecharge.TextMarginLeft = 0;
            this.btnRecharge.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnRecharge.UseDefaultRadiusAndThickness = true;
            this.btnRecharge.Click += new System.EventHandler(this.btnRecharge_Click);
            // 
            // txtMoney
            // 
            this.txtMoney.AcceptsReturn = false;
            this.txtMoney.AcceptsTab = false;
            this.txtMoney.AnimationSpeed = 200;
            this.txtMoney.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMoney.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMoney.AutoSizeHeight = true;
            this.txtMoney.BackColor = System.Drawing.Color.Transparent;
            this.txtMoney.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMoney.BackgroundImage")));
            this.txtMoney.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtMoney.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMoney.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMoney.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMoney.BorderRadius = 40;
            this.txtMoney.BorderThickness = 1;
            this.txtMoney.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMoney.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMoney.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtMoney.DefaultText = "";
            this.txtMoney.FillColor = System.Drawing.Color.White;
            this.txtMoney.HideSelection = true;
            this.txtMoney.IconLeft = null;
            this.txtMoney.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMoney.IconPadding = 10;
            this.txtMoney.IconRight = null;
            this.txtMoney.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMoney.Lines = new string[0];
            this.txtMoney.Location = new System.Drawing.Point(295, 61);
            this.txtMoney.MaxLength = 32767;
            this.txtMoney.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMoney.Modified = false;
            this.txtMoney.Multiline = false;
            this.txtMoney.Name = "txtMoney";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMoney.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMoney.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMoney.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMoney.OnIdleState = stateProperties8;
            this.txtMoney.Padding = new System.Windows.Forms.Padding(3);
            this.txtMoney.PasswordChar = '\0';
            this.txtMoney.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMoney.PlaceholderText = "The amount of money";
            this.txtMoney.ReadOnly = false;
            this.txtMoney.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMoney.SelectedText = "";
            this.txtMoney.SelectionLength = 0;
            this.txtMoney.SelectionStart = 0;
            this.txtMoney.ShortcutsEnabled = true;
            this.txtMoney.Size = new System.Drawing.Size(249, 39);
            this.txtMoney.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMoney.TabIndex = 1;
            this.txtMoney.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMoney.TextMarginBottom = 0;
            this.txtMoney.TextMarginLeft = 3;
            this.txtMoney.TextMarginTop = 1;
            this.txtMoney.TextPlaceholder = "The amount of money";
            this.txtMoney.UseSystemPasswordChar = false;
            this.txtMoney.WordWrap = true;
            // 
            // pbMoneyAmount
            // 
            this.pbMoneyAmount.Image = global::Window_Project_v5._1.Properties.Resources.money2;
            this.pbMoneyAmount.Location = new System.Drawing.Point(178, 42);
            this.pbMoneyAmount.Name = "pbMoneyAmount";
            this.pbMoneyAmount.Size = new System.Drawing.Size(80, 80);
            this.pbMoneyAmount.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbMoneyAmount.TabIndex = 0;
            this.pbMoneyAmount.TabStop = false;
            // 
            // pbMoneyTotal
            // 
            this.pbMoneyTotal.Image = global::Window_Project_v5._1.Properties.Resources.money;
            this.pbMoneyTotal.Location = new System.Drawing.Point(550, 12);
            this.pbMoneyTotal.Name = "pbMoneyTotal";
            this.pbMoneyTotal.Size = new System.Drawing.Size(100, 64);
            this.pbMoneyTotal.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbMoneyTotal.TabIndex = 0;
            this.pbMoneyTotal.TabStop = false;
            // 
            // pbAvatar
            // 
            this.pbAvatar.AllowFocused = false;
            this.pbAvatar.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pbAvatar.AutoSizeHeight = true;
            this.pbAvatar.BorderRadius = 32;
            this.pbAvatar.Image = ((System.Drawing.Image)(resources.GetObject("pbAvatar.Image")));
            this.pbAvatar.IsCircle = true;
            this.pbAvatar.Location = new System.Drawing.Point(42, 12);
            this.pbAvatar.Margin = new System.Windows.Forms.Padding(2);
            this.pbAvatar.Name = "pbAvatar";
            this.pbAvatar.Size = new System.Drawing.Size(64, 64);
            this.pbAvatar.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbAvatar.TabIndex = 11;
            this.pbAvatar.TabStop = false;
            this.pbAvatar.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // panelTop
            // 
            this.panelTop.Controls.Add(this.gbInfo);
            this.panelTop.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelTop.Location = new System.Drawing.Point(0, 0);
            this.panelTop.Name = "panelTop";
            this.panelTop.Size = new System.Drawing.Size(931, 111);
            this.panelTop.TabIndex = 4;
            // 
            // panelBody
            // 
            this.panelBody.Controls.Add(this.gbFunction);
            this.panelBody.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelBody.Location = new System.Drawing.Point(0, 111);
            this.panelBody.Name = "panelBody";
            this.panelBody.Size = new System.Drawing.Size(931, 459);
            this.panelBody.TabIndex = 5;
            // 
            // btn50
            // 
            this.btn50.AllowAnimations = true;
            this.btn50.AllowMouseEffects = true;
            this.btn50.AllowToggling = false;
            this.btn50.AnimationSpeed = 200;
            this.btn50.AutoGenerateColors = false;
            this.btn50.AutoRoundBorders = false;
            this.btn50.AutoSizeLeftIcon = true;
            this.btn50.AutoSizeRightIcon = true;
            this.btn50.BackColor = System.Drawing.Color.Transparent;
            this.btn50.BackColor1 = System.Drawing.Color.Transparent;
            this.btn50.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn50.BackgroundImage")));
            this.btn50.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn50.ButtonText = "50,000 VND";
            this.btn50.ButtonTextMarginLeft = 0;
            this.btn50.ColorContrastOnClick = 45;
            this.btn50.ColorContrastOnHover = 45;
            this.btn50.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btn50.CustomizableEdges = borderEdges4;
            this.btn50.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn50.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn50.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn50.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn50.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn50.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(88)))), ((int)(((byte)(168)))), ((int)(((byte)(176)))));
            this.btn50.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn50.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn50.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn50.IconMarginLeft = 11;
            this.btn50.IconPadding = 10;
            this.btn50.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn50.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn50.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn50.IconSize = 25;
            this.btn50.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(88)))), ((int)(((byte)(168)))), ((int)(((byte)(176)))));
            this.btn50.IdleBorderRadius = 35;
            this.btn50.IdleBorderThickness = 2;
            this.btn50.IdleFillColor = System.Drawing.Color.Transparent;
            this.btn50.IdleIconLeftImage = null;
            this.btn50.IdleIconRightImage = null;
            this.btn50.IndicateFocus = false;
            this.btn50.Location = new System.Drawing.Point(588, 57);
            this.btn50.Margin = new System.Windows.Forms.Padding(2);
            this.btn50.Name = "btn50";
            this.btn50.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn50.OnDisabledState.BorderRadius = 35;
            this.btn50.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn50.OnDisabledState.BorderThickness = 2;
            this.btn50.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn50.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn50.OnDisabledState.IconLeftImage = null;
            this.btn50.OnDisabledState.IconRightImage = null;
            this.btn50.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(88)))), ((int)(((byte)(168)))), ((int)(((byte)(176)))));
            this.btn50.onHoverState.BorderRadius = 35;
            this.btn50.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn50.onHoverState.BorderThickness = 2;
            this.btn50.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(88)))), ((int)(((byte)(168)))), ((int)(((byte)(176)))));
            this.btn50.onHoverState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btn50.onHoverState.IconLeftImage = null;
            this.btn50.onHoverState.IconRightImage = null;
            this.btn50.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(88)))), ((int)(((byte)(168)))), ((int)(((byte)(176)))));
            this.btn50.OnIdleState.BorderRadius = 35;
            this.btn50.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn50.OnIdleState.BorderThickness = 2;
            this.btn50.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btn50.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(88)))), ((int)(((byte)(168)))), ((int)(((byte)(176)))));
            this.btn50.OnIdleState.IconLeftImage = null;
            this.btn50.OnIdleState.IconRightImage = null;
            this.btn50.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(88)))), ((int)(((byte)(168)))), ((int)(((byte)(176)))));
            this.btn50.OnPressedState.BorderRadius = 35;
            this.btn50.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn50.OnPressedState.BorderThickness = 2;
            this.btn50.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btn50.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(88)))), ((int)(((byte)(168)))), ((int)(((byte)(176)))));
            this.btn50.OnPressedState.IconLeftImage = null;
            this.btn50.OnPressedState.IconRightImage = null;
            this.btn50.Size = new System.Drawing.Size(156, 43);
            this.btn50.TabIndex = 6;
            this.btn50.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn50.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn50.TextMarginLeft = 0;
            this.btn50.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn50.UseDefaultRadiusAndThickness = true;
            this.btn50.Click += new System.EventHandler(this.btn50_Click);
            // 
            // btn100
            // 
            this.btn100.AllowAnimations = true;
            this.btn100.AllowMouseEffects = true;
            this.btn100.AllowToggling = false;
            this.btn100.AnimationSpeed = 200;
            this.btn100.AutoGenerateColors = false;
            this.btn100.AutoRoundBorders = false;
            this.btn100.AutoSizeLeftIcon = true;
            this.btn100.AutoSizeRightIcon = true;
            this.btn100.BackColor = System.Drawing.Color.Transparent;
            this.btn100.BackColor1 = System.Drawing.Color.Transparent;
            this.btn100.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn100.BackgroundImage")));
            this.btn100.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn100.ButtonText = "100,000 VND";
            this.btn100.ButtonTextMarginLeft = 0;
            this.btn100.ColorContrastOnClick = 45;
            this.btn100.ColorContrastOnHover = 45;
            this.btn100.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btn100.CustomizableEdges = borderEdges3;
            this.btn100.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn100.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn100.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn100.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn100.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn100.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn100.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(201)))), ((int)(((byte)(62)))));
            this.btn100.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn100.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn100.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn100.IconMarginLeft = 11;
            this.btn100.IconPadding = 10;
            this.btn100.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn100.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn100.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn100.IconSize = 25;
            this.btn100.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(201)))), ((int)(((byte)(62)))));
            this.btn100.IdleBorderRadius = 35;
            this.btn100.IdleBorderThickness = 2;
            this.btn100.IdleFillColor = System.Drawing.Color.Transparent;
            this.btn100.IdleIconLeftImage = null;
            this.btn100.IdleIconRightImage = null;
            this.btn100.IndicateFocus = false;
            this.btn100.Location = new System.Drawing.Point(588, 114);
            this.btn100.Margin = new System.Windows.Forms.Padding(2);
            this.btn100.Name = "btn100";
            this.btn100.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn100.OnDisabledState.BorderRadius = 35;
            this.btn100.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn100.OnDisabledState.BorderThickness = 2;
            this.btn100.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn100.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn100.OnDisabledState.IconLeftImage = null;
            this.btn100.OnDisabledState.IconRightImage = null;
            this.btn100.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(201)))), ((int)(((byte)(62)))));
            this.btn100.onHoverState.BorderRadius = 35;
            this.btn100.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn100.onHoverState.BorderThickness = 2;
            this.btn100.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(201)))), ((int)(((byte)(62)))));
            this.btn100.onHoverState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btn100.onHoverState.IconLeftImage = null;
            this.btn100.onHoverState.IconRightImage = null;
            this.btn100.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(201)))), ((int)(((byte)(62)))));
            this.btn100.OnIdleState.BorderRadius = 35;
            this.btn100.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn100.OnIdleState.BorderThickness = 2;
            this.btn100.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btn100.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(201)))), ((int)(((byte)(62)))));
            this.btn100.OnIdleState.IconLeftImage = null;
            this.btn100.OnIdleState.IconRightImage = null;
            this.btn100.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(201)))), ((int)(((byte)(62)))));
            this.btn100.OnPressedState.BorderRadius = 35;
            this.btn100.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn100.OnPressedState.BorderThickness = 2;
            this.btn100.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btn100.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(86)))), ((int)(((byte)(201)))), ((int)(((byte)(62)))));
            this.btn100.OnPressedState.IconLeftImage = null;
            this.btn100.OnPressedState.IconRightImage = null;
            this.btn100.Size = new System.Drawing.Size(156, 43);
            this.btn100.TabIndex = 7;
            this.btn100.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn100.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn100.TextMarginLeft = 0;
            this.btn100.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn100.UseDefaultRadiusAndThickness = true;
            this.btn100.Click += new System.EventHandler(this.btn100_Click);
            // 
            // btn200
            // 
            this.btn200.AllowAnimations = true;
            this.btn200.AllowMouseEffects = true;
            this.btn200.AllowToggling = false;
            this.btn200.AnimationSpeed = 200;
            this.btn200.AutoGenerateColors = false;
            this.btn200.AutoRoundBorders = false;
            this.btn200.AutoSizeLeftIcon = true;
            this.btn200.AutoSizeRightIcon = true;
            this.btn200.BackColor = System.Drawing.Color.Transparent;
            this.btn200.BackColor1 = System.Drawing.Color.Transparent;
            this.btn200.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn200.BackgroundImage")));
            this.btn200.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn200.ButtonText = "200,000 VND";
            this.btn200.ButtonTextMarginLeft = 0;
            this.btn200.ColorContrastOnClick = 45;
            this.btn200.ColorContrastOnHover = 45;
            this.btn200.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btn200.CustomizableEdges = borderEdges2;
            this.btn200.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn200.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn200.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn200.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn200.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn200.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn200.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(190)))), ((int)(((byte)(45)))));
            this.btn200.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn200.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn200.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn200.IconMarginLeft = 11;
            this.btn200.IconPadding = 10;
            this.btn200.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn200.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn200.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn200.IconSize = 25;
            this.btn200.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(190)))), ((int)(((byte)(45)))));
            this.btn200.IdleBorderRadius = 35;
            this.btn200.IdleBorderThickness = 2;
            this.btn200.IdleFillColor = System.Drawing.Color.Transparent;
            this.btn200.IdleIconLeftImage = null;
            this.btn200.IdleIconRightImage = null;
            this.btn200.IndicateFocus = false;
            this.btn200.Location = new System.Drawing.Point(588, 176);
            this.btn200.Margin = new System.Windows.Forms.Padding(2);
            this.btn200.Name = "btn200";
            this.btn200.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn200.OnDisabledState.BorderRadius = 35;
            this.btn200.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn200.OnDisabledState.BorderThickness = 2;
            this.btn200.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn200.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn200.OnDisabledState.IconLeftImage = null;
            this.btn200.OnDisabledState.IconRightImage = null;
            this.btn200.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(190)))), ((int)(((byte)(45)))));
            this.btn200.onHoverState.BorderRadius = 35;
            this.btn200.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn200.onHoverState.BorderThickness = 2;
            this.btn200.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(190)))), ((int)(((byte)(45)))));
            this.btn200.onHoverState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btn200.onHoverState.IconLeftImage = null;
            this.btn200.onHoverState.IconRightImage = null;
            this.btn200.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(190)))), ((int)(((byte)(45)))));
            this.btn200.OnIdleState.BorderRadius = 35;
            this.btn200.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn200.OnIdleState.BorderThickness = 2;
            this.btn200.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btn200.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(190)))), ((int)(((byte)(45)))));
            this.btn200.OnIdleState.IconLeftImage = null;
            this.btn200.OnIdleState.IconRightImage = null;
            this.btn200.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(190)))), ((int)(((byte)(45)))));
            this.btn200.OnPressedState.BorderRadius = 35;
            this.btn200.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn200.OnPressedState.BorderThickness = 2;
            this.btn200.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btn200.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(207)))), ((int)(((byte)(190)))), ((int)(((byte)(45)))));
            this.btn200.OnPressedState.IconLeftImage = null;
            this.btn200.OnPressedState.IconRightImage = null;
            this.btn200.Size = new System.Drawing.Size(156, 43);
            this.btn200.TabIndex = 8;
            this.btn200.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn200.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn200.TextMarginLeft = 0;
            this.btn200.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn200.UseDefaultRadiusAndThickness = true;
            this.btn200.Click += new System.EventHandler(this.btn200_Click);
            // 
            // btn500
            // 
            this.btn500.AllowAnimations = true;
            this.btn500.AllowMouseEffects = true;
            this.btn500.AllowToggling = false;
            this.btn500.AnimationSpeed = 200;
            this.btn500.AutoGenerateColors = false;
            this.btn500.AutoRoundBorders = false;
            this.btn500.AutoSizeLeftIcon = true;
            this.btn500.AutoSizeRightIcon = true;
            this.btn500.BackColor = System.Drawing.Color.Transparent;
            this.btn500.BackColor1 = System.Drawing.Color.Transparent;
            this.btn500.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn500.BackgroundImage")));
            this.btn500.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn500.ButtonText = "500,000 VND";
            this.btn500.ButtonTextMarginLeft = 0;
            this.btn500.ColorContrastOnClick = 45;
            this.btn500.ColorContrastOnHover = 45;
            this.btn500.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btn500.CustomizableEdges = borderEdges1;
            this.btn500.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn500.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn500.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn500.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn500.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btn500.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn500.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.btn500.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn500.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn500.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn500.IconMarginLeft = 11;
            this.btn500.IconPadding = 10;
            this.btn500.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn500.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn500.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn500.IconSize = 25;
            this.btn500.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.btn500.IdleBorderRadius = 35;
            this.btn500.IdleBorderThickness = 2;
            this.btn500.IdleFillColor = System.Drawing.Color.Transparent;
            this.btn500.IdleIconLeftImage = null;
            this.btn500.IdleIconRightImage = null;
            this.btn500.IndicateFocus = false;
            this.btn500.Location = new System.Drawing.Point(588, 237);
            this.btn500.Margin = new System.Windows.Forms.Padding(2);
            this.btn500.Name = "btn500";
            this.btn500.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn500.OnDisabledState.BorderRadius = 35;
            this.btn500.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn500.OnDisabledState.BorderThickness = 2;
            this.btn500.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn500.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn500.OnDisabledState.IconLeftImage = null;
            this.btn500.OnDisabledState.IconRightImage = null;
            this.btn500.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.btn500.onHoverState.BorderRadius = 35;
            this.btn500.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn500.onHoverState.BorderThickness = 2;
            this.btn500.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.btn500.onHoverState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btn500.onHoverState.IconLeftImage = null;
            this.btn500.onHoverState.IconRightImage = null;
            this.btn500.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.btn500.OnIdleState.BorderRadius = 35;
            this.btn500.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn500.OnIdleState.BorderThickness = 2;
            this.btn500.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btn500.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.btn500.OnIdleState.IconLeftImage = null;
            this.btn500.OnIdleState.IconRightImage = null;
            this.btn500.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.btn500.OnPressedState.BorderRadius = 35;
            this.btn500.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btn500.OnPressedState.BorderThickness = 2;
            this.btn500.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btn500.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(186)))), ((int)(((byte)(52)))), ((int)(((byte)(52)))));
            this.btn500.OnPressedState.IconLeftImage = null;
            this.btn500.OnPressedState.IconRightImage = null;
            this.btn500.Size = new System.Drawing.Size(156, 43);
            this.btn500.TabIndex = 9;
            this.btn500.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn500.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn500.TextMarginLeft = 0;
            this.btn500.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn500.UseDefaultRadiusAndThickness = true;
            this.btn500.Click += new System.EventHandler(this.btn500_Click);
            // 
            // FMoney
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(931, 570);
            this.Controls.Add(this.panelBody);
            this.Controls.Add(this.panelTop);
            this.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.Name = "FMoney";
            this.Text = "FMoney";
            this.Load += new System.EventHandler(this.FMoney_Load);
            this.gbInfo.ResumeLayout(false);
            this.gbInfo.PerformLayout();
            this.gbFunction.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbMoneyAmount)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbMoneyTotal)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pbAvatar)).EndInit();
            this.panelTop.ResumeLayout(false);
            this.panelBody.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.PictureBox pbMoneyTotal;
        private Bunifu.UI.WinForms.BunifuGroupBox gbInfo;
        private System.Windows.Forms.Label lblTotalMoney;
        private System.Windows.Forms.Label lblName;
        private Bunifu.UI.WinForms.BunifuGroupBox gbFunction;
        private System.Windows.Forms.PictureBox pbMoneyAmount;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnRecharge;
        private Bunifu.UI.WinForms.BunifuTextBox txtMoney;
        private Bunifu.UI.WinForms.BunifuPictureBox pbAvatar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnWithdraw;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuTextBox txtPassword;
        private System.Windows.Forms.Panel panelTop;
        private System.Windows.Forms.Panel panelBody;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn50;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn500;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn200;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btn100;
    }
}